# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-16 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u6c14\u4f53\u540d\u79f0')),
                ('value', models.CharField(max_length=10, verbose_name='\u6c14\u4f53\u6d53\u5ea6')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u91c7\u96c6\u6570\u636e\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u4fe1\u606f',
                'verbose_name_plural': '\u6570\u636e\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g1', models.CharField(max_length=5, verbose_name='\u7ee7\u7535\u56681')),
                ('g2', models.CharField(max_length=5, verbose_name='\u7ee7\u7535\u56682')),
            ],
            options={
                'verbose_name': '\u7528\u7535\u5668\u72b6\u6001',
                'verbose_name_plural': '\u7528\u7535\u5668\u72b6\u6001',
            },
        ),
    ]
