# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-19 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('time',), 'verbose_name': '\u6570\u636e\u4fe1\u606f', 'verbose_name_plural': '\u6570\u636e\u4fe1\u606f'},
        ),
    ]
