# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotSystem', '0002_auto_20180319_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(max_length=20, verbose_name='\u6c14\u4f53\u6d53\u5ea6'),
        ),
    ]
