# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotSystem', '0006_remove_data_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ch4',
        ),
        migrations.AddField(
            model_name='data',
            name='jingdu',
            field=models.CharField(default='', max_length=20, verbose_name='\u7ecf\u5ea6'),
        ),
        migrations.AddField(
            model_name='data',
            name='pm',
            field=models.CharField(default='', max_length=20, verbose_name='\u7c89\u5c18'),
        ),
        migrations.AddField(
            model_name='data',
            name='weidu',
            field=models.CharField(default='', max_length=20, verbose_name='\u7ef4\u5ea6'),
        ),
    ]
