# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-26 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotSystem', '0007_auto_20180512_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentvalue', models.CharField(default='', max_length=10, verbose_name='\u62a5\u8b66\u5e73\u5747\u503c')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u62a5\u8b66\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u62a5\u8b66\u4fe1\u606f\u8bb0\u5f55',
                'verbose_name_plural': '\u62a5\u8b66\u4fe1\u606f\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailtitle', models.CharField(default='\u6d53\u5ea6\u8d85\u6807\u4e86', max_length=50, verbose_name='\u90ae\u4ef6\u6807\u9898')),
                ('messageContent', models.TextField(default='\u62a5\u8b66\uff01', verbose_name='\u62a5\u8b66\u5185\u5bb9')),
                ('value', models.IntegerField(default=100, verbose_name='\u9608\u503c')),
                ('interval', models.IntegerField(default=10, verbose_name='\u62a5\u8b66\u65f6\u95f4\u95f4\u9694')),
                ('level', models.CharField(choices=[('primary', '\u521d\u7ea7\u62a5\u8b66'), ('serious', '\u4e25\u91cd\u62a5\u8b66'), ('fatal', '\u81f4\u547d\u62a5\u8b66')], default='primary', max_length=20, verbose_name='\u62a5\u8b66\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u62a5\u8b66\u4fe1\u606f',
                'verbose_name_plural': '\u62a5\u8b66\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='savewarning',
            name='warning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotSystem.Warning', verbose_name='\u6240\u5c5e\u62a5\u8b66'),
        ),
    ]
